modLoader="javafml"

loaderVersion="[28,)"
license="GNU GENERAL PUBLIC LICENSE"

[[mods]]
modId="danmachi"
version="${file.jarVersion}"
displayName="Danmachi Mod"
authors="ImNotJahan"
description='''
Adds vodka. That's about it.
'''
